#!/bin/bash

if [ $# -eq 2 ]; then 
  var=`mpls nhlfe show | grep -B  1 $2 | grep key | awk '{print $4}'`
  iptables -t mangle -A FORWARD -d $1 -j mpls --nhlfe $var

elif [ $# -eq 3 ]; then 
  var=`mpls nhlfe show | grep -B  1 $3 | grep key | awk '{print $4}'`
  iptables -t mangle -A FORWARD -s $1 -d $2 -j mpls --nhlfe $var

elif [ $# -eq 4 ]; then 
	var1=`mpls nhlfe add key 0 instructions push gen $2 nexthop $3 ipv4 $4 | grep key |cut -c 17-26`
	var2=`iptables -t mangle --line-numbers -L FORWARD | grep mpls | grep $1 | awk '{print $1}'`
	if [ -n "$var2" ];then
		iptables -t mangle -D FORWARD $var2
	fi
	iptables -t mangle -A FORWARD -d $1 -j mpls --nhlfe $var1

elif [ $# -eq 5 ]; then 
	var1=`mpls nhlfe add key 0 instructions push gen $3 nexthop $4 ipv4 $5 | grep key |cut -c 17-26`
	var2=`iptables -t mangle --line-numbers -L FORWARD | grep mpls | grep $1 | grep $2 |awk '{print $1}'`
	if [ -n "$var2" ];then
		iptables -t mangle -D FORWARD $var2
	fi
	iptables -t mangle -A FORWARD -s $1 -d $2 -j mpls --nhlfe $var1

else 
	echo "the number of parameter must be 5 or 6!"
fi



